# Generated by Django 2.2.5 on 2019-10-17 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20191009_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemtestcase',
            name='datatype',
        ),
        migrations.AddField(
            model_name='problem',
            name='datatype',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
