# Generated by Django 2.2.5 on 2019-10-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20191022_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='user',
            new_name='submitted',
        ),
    ]
