# Generated by Django 2.2.5 on 2019-10-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20191028_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='submitted',
            new_name='user',
        ),
    ]
