# Generated by Django 2.2.5 on 2019-11-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20191029_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='datatype',
            field=models.CharField(choices=[('string', 'String'), ('int', 'Int'), ('float', 'Float'), ('array', 'Array'), ('matrix', 'Matrix'), ('linkedlist', 'Linked List')], default='string', max_length=15),
        ),
    ]
