# Generated by Django 2.2.5 on 2019-11-13 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_auto_20191113_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to=settings.AUTH_USER_MODEL),
        ),
    ]
