# Generated by Django 2.2.5 on 2019-11-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20191028_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='language',
            field=models.CharField(choices=[('JavaScript', 'JavaScript'), ('C++', 'C++'), ('C', 'C'), ('Python', 'Python'), ('Clojure', 'Clojure'), ('Java', 'Java'), ('C#', 'C#')], default='Java', max_length=50),
        ),
    ]
