# Generated by Django 2.2.5 on 2019-11-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_auto_20191104_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='language',
            field=models.CharField(choices=[('C#', 'C#'), ('Java', 'Java'), ('C++', 'C++'), ('Python', 'Python'), ('C', 'C'), ('Clojure', 'Clojure'), ('JavaScript', 'JavaScript')], default='Java', max_length=50),
        ),
    ]
