# Generated by Django 2.2.5 on 2019-11-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_auto_20191104_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='language',
            field=models.CharField(choices=[('Java', 'Java'), ('C#', 'C#'), ('Clojure', 'Clojure'), ('C', 'C'), ('Python', 'Python'), ('JavaScript', 'JavaScript'), ('C++', 'C++')], default='Java', max_length=50),
        ),
    ]
