# Generated by Django 2.2.5 on 2019-11-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_auto_20191104_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='language',
            field=models.CharField(choices=[('C#', 'C#'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('C++', 'C++'), ('C', 'C'), ('Python', 'Python'), ('Clojure', 'Clojure')], default='Java', max_length=50),
        ),
    ]
