# Generated by Django 2.2.5 on 2019-11-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_auto_20191119_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='language',
            field=models.CharField(choices=[('JavaScript', 'JavaScript'), ('C', 'C'), ('C#', 'C#'), ('Clojure', 'Clojure'), ('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++')], default='Java', max_length=50),
        ),
    ]
