# Generated by Django 2.2.5 on 2019-11-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_auto_20191113_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='language',
            field=models.CharField(choices=[('C#', 'C#'), ('Java', 'Java'), ('C++', 'C++'), ('Python', 'Python'), ('JavaScript', 'JavaScript'), ('C', 'C'), ('Clojure', 'Clojure')], default='Java', max_length=50),
        ),
    ]
