# Generated by Django 2.2.5 on 2019-11-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_auto_20191114_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='language',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('JavaScript', 'JavaScript'), ('C', 'C'), ('Clojure', 'Clojure'), ('C#', 'C#'), ('C++', 'C++')], default='Java', max_length=50),
        ),
    ]
