# Generated by Django 2.2.5 on 2019-11-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_auto_20191116_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='language',
            field=models.CharField(choices=[('JavaScript', 'JavaScript'), ('C#', 'C#'), ('Python', 'Python'), ('C++', 'C++'), ('Clojure', 'Clojure'), ('C', 'C'), ('Java', 'Java')], default='Java', max_length=50),
        ),
    ]
