# Generated by Django 2.2.5 on 2019-12-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_auto_20191119_1717'),
        ('editor', '0011_auto_20191121_1939'),
    ]

    operations = [
    ]
