# Generated by Django 2.2.5 on 2019-12-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0012_merge_20191222_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='language',
            field=models.CharField(choices=[('C', 'C'), ('C#', 'C#'), ('Java', 'Java'), ('C++', 'C++'), ('Clojure', 'Clojure'), ('JavaScript', 'JavaScript'), ('Python', 'Python')], default='Java', max_length=50),
        ),
    ]
